<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<PublishAot>true</PublishAot>  <!-- Enable Native AOT -->
    <SelfContained>false</SelfContained> <!-- For PS4, likely false -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Other\" />
  </ItemGroup>

</Project>
