using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// CREATOR NOTE : 
// 8-28-26 MADE FOR VOICE COMMUNICATION AND OTHER HIGH SPEED COMMUNICATION
// THIS IS A GENERAL CLASS FOR OUR CLIENTS OVER UDP 
// IT MIGHT JUST BE A HOLDER FOR BOTH CLIENT AND SERVER LIKE OUR PEER.cs 
// SINCE UDP IS CONNECTIONLESS WE CAN THEREFORE EASILY HAVE BOTH A SERVER AND A CLIENT 


namespace NETConnect
{
    

    public class UDPPeer
    {
        // PASS REFERENCE TO PEER SO WE HAVE ACCESS TO EVERYTHING NEEDED FOR OTHER COMMUNICATIONS ASWELL 

        // CREATE A BASE UDP PEER FOR HANDLING STANDARD COMMUNICATION
        // GOING DO THAT NOW 
    }
}
